# This is a basic workflow to help you get started with Actions

name: Analyze Bundle Size

# Controls when the action will run.
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  analyze:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Install
        uses: bahmutov/npm-install@v1

      # Runs a set of commands using the runners shell
      - name: Build & analyze
        run: mkdir -p .next/analyze && npm run analyze | tee .next/analyze/output.txt

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: client.html
          path: .next/analyze/client.html

      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1.0.2
        id: find-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get comment body
        id: get-comment-body
        env:
          PR: ${{ steps.find-pr.outputs.number }}
          PR2: ${{ github.event.number }}
        run: |
          echo "PR IS $PR"
          echo "PR2 IS $PR2"
          body=$(echo "\`\`\`\n`sed '1,/Page/d' yo.txt`\n\`\`\`")
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && steps.find-pr.outputs.number
        with:
          issue-number: ${{ steps.find-pr.outputs.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
