# This is a basic workflow to help you get started with Actions

name: Analyze

# Controls when the action will run. 
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  analyze:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      
      - name: Install
        run: npm install && mkdir -p .next/analyze
        
      # Runs a set of commands using the runners shell
      - name: Build & analyze
        run: npm run analyze | tee .next/analyze/output.txt
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: client.html
          path: .next/analyze/
